#!/usr/bin/perl -s

use IO::Socket;

$socket = IO::Socket::INET->new (
    PeerAddr => "setup.yandex.net",
    PeerPort => 80,
    Type => SOCK_STREAM) or die "Cannot connect to setup.yandex.net for rebase: $@\n";

$req = <<EOF;
GET /cgi-bin/get_monitoring_master HTTP/1.0

EOF

print $socket $req;

while (<$socket>) {
    chomp;
    last if /^\s*$/;
}

$srv = <$socket>;
print "Got new monitor server name: $srv";

close ($socket);

open (FD, ">/etc/zabbix/server.conf") or die "Cannot open config file for update\n";
print FD "Server=$srv";
close (FD);
