#!/bin/bash
#
# Init file for zabbix_agent daemon
#
# chkconfig: 2345 30 70
# description: zabbix_agent daemon
#
# processname: zabbix_agentd
# config: /etc/zabbix/zabbix_agentd.conf
# pidfile: /var/run/zabbix/zabbix_agentd.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="zabbix_agentd"

PID_FILE=/var/run/zabbix-agent/zabbix_agentd.pid
BASEDIR=/usr/sbin
ZABBIX_AGENTD=$BASEDIR/zabbix_agentd

runlevel=$(set -- $(runlevel); eval "echo \$$#" )

[ -d /var/run/zabbix-agent ] || mkdir /var/run/zabbix-agent && chown monitor:monitor /var/run/zabbix-agent

start()
{
	echo -n $"Starting $prog: "
	$ZABBIX_AGENTD && success || failure
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop()
{
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE $ZABBIX_AGENTD
	RETVAL=$?
	# if we are in halt or reboot runlevel kill all running sessions
	# so the TCP connections are closed cleanly
	if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
	    killall $prog 2>/dev/null
	fi
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $ZABBIX_AGENTD $PID_FILE
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
esac
exit $RETVAL
