#!/bin/bash
#
# Init file for zabbix_server daemon
#
# chkconfig: 2345 25 75
# description: zabbix_server daemon
#
# processname: zabbix_server
# config: /etc/zabbix/zabbix_server.conf
# pidfile: /var/run/sshd.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="zabbix_server"

# Some functions to make the below more readable
BASEDIR=/usr/sbin
ZABBIX_SERVER=$BASEDIR/zabbix_server
PID_FILE=/var/run/zabbix-server/zabbix_server.pid

runlevel=$(set -- $(runlevel); eval "echo \$$#" )

[ -d /var/run/zabbix-server ] || mkdir /var/run/zabbix-server && chown zabbix:zabbix /var/run/zabbix-server

start()
{
	# Create keys if necessary
	echo -n $"Starting $prog: "
	$ZABBIX_SERVER && success || failure
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop()
{
	echo -n $"Stopping $prog: "
	killproc -p $PID_FILE $ZABBIX_SERVER
	RETVAL=$?
	# if we are in halt or reboot runlevel kill all running sessions
	# so the TCP connections are closed cleanly
	if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
	    killall $prog 2>/dev/null
	fi
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $ZABBIX_SERVER $PID_FILE
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
esac
exit $RETVAL
