#!/bin/sh

case ${1:-incorrect} in
    sarge|etch|lenny|feisty|gutsy|hardy|intrepid|jaunty)
        ;;
    *)
        echo "You must specify valid distro as first argument (sarge, etch, lenny, feisty, gutsy, hardy, intrepid, jaunty)"
        exit 1
esac

DIR=$(dirname $0)
[ -L $DIR/control ] && rm $DIR/control && ln -s control.$1 $DIR/control

VER=$(cat $DIR/control | grep -e '^Version:' | head -n 1 | cut -d ' ' -f 2)

[ a$VER = a ] && ( echo Not found version tag in control file. Failed.; exit 1 )
cat $DIR/changelog | sed "1s/(.*) unstable/(1:$VER) $1/" > $DIR/changelog.new && mv $DIR/changelog.new $DIR/changelog