#!/bin/sh

CONFFILE1="/usr/share/zabbix-agent/zabbix_agentd.conf"
CONFFILE_DEST1="/etc/zabbix/zabbix_agentd.conf"

CONFFILE2="/usr/share/zabbix-agent/zabbix_agent.conf"
CONFFILE_DEST2="/etc/zabbix/zabbix_agent.conf"

. /usr/share/debconf/confmodule
db_version 2.0 || [ $? -lt 30 ]

UNAME=monitor
GNAME=monitor

if [ "$1" = "configure" ]; then

    RET=""
    db_get zabbix-agent/server || true
    zabbix_server="$RET"
    if [ "$zabbix_server" = "" ]; then
        zabbix_server="localhost"
    fi

    zabbix_hostname=$(hostname -f)

    sed "s/^[# ]*Server=.*/Server=$zabbix_server/g; s/^[# ]*Hostname=.*/Hostname=$zabbix_hostname/g" < $CONFFILE1 > $CONFFILE_DEST1.new 
    ucf --debconf-ok $CONFFILE_DEST1.new $CONFFILE_DEST1
    rm -f $CONFFILE_DEST1.new

    sed "s/^[# ]*Server=.*/Server=$zabbix_server/g; s/^[# ]*Hostname=.*/Hostname=$zabbix_hostname/g" < $CONFFILE2 > $CONFFILE_DEST2.new 
    ucf --debconf-ok $CONFFILE_DEST2.new $CONFFILE_DEST2
    rm -f $CONFFILE_DEST2.new
    
    if ! getent group $GNAME > /dev/null 2>&1 ; then
    addgroup --system --quiet $GNAME
    fi

    if ! getent passwd $UNAME > /dev/null 2>&1 ; then
    adduser --quiet \
        --ingroup $GNAME \
        $UNAME
    fi
    chown $UNAME:$GNAME /var/log/zabbix-agent -R
    chown $UNAME:$GNAME /var/run/zabbix-agent -R
    chown $UNAME:$GNAME /var/spool/zabbix -R
    chown $UNAME:$GNAME /etc/zabbix/conf.d -R

    # Temporary hack for migration on monitor user (REMOVE THIS)
    # clean ipcs (semaphores)
    ipcs -s | grep zabbix | sed 's/  */ /g' | cut -d ' ' -f 2 | while read key; do ipcrm -s $key; done
    # shared memory segments
    ipcs -m | grep zabbix | sed 's/  */ /g' | cut -d ' ' -f 2 | while read key; do ipcrm -m $key; done

    # run zabbix-rebase-server
    /usr/sbin/zabbix-rebase-server
fi

db_stop

#DEBHELPER#

exit 0
