#!/bin/sh
# Script was taken from mysql323-server port, and modified
# to suit zabbix needs

[ -n "${PACKAGE_BUILDING}" ] && exit 0

[ "${2}" = "POST-INSTALL" ] && exit 0

PATH=/bin:/usr/sbin

USER=monitor
GROUP=${USER}

if pw group show "${GROUP}" 2>/dev/null; then
        echo "You already have a group \"${GROUP}\", so I will use it."
else
        if pw groupadd ${GROUP}; then
                echo "Added group \"${GROUP}\"."
        else
                echo "Adding group \"${GROUP}\" failed..."
                exit 1
        fi
fi

if pw user show "${USER}" 2>/dev/null; then
        echo "You already have a user \"${USER}\", so I will use it."
else
        if pw useradd ${USER} -g ${GROUP} -h - \
                -c "Monitoring user created by zabbix"
        then
                echo "Added user \"${USER}\"."
        else
                echo "Adding user \"${USER}\" failed..."
                exit 1
        fi
fi
