#!/bin/sh
# Script was taken from mysql323-server port, and modified
# to suit zabbix needs

[ -n "${PACKAGE_BUILDING}" ] && exit 0

PATH=/bin:/usr/sbin

USER=monitor
GROUP=${USER}

# change owner for installed empty directories
chown -R monitor:monitor /var/run/zabbix /var/log/zabbix
[ -d /etc/zabbix/conf.d ] || mkdir /etc/zabbix/conf.d
chown -R monitor:monitor /etc/zabbix/conf.d/

# replace hostname in config file to FQDN
NAME=$(hostname -f)
CONF=/etc/zabbix/zabbix_agentd.conf
PATH=/usr/bin:/usr/local/bin:$PATH

cat $CONF | sed "s/^Hostname=.*$/Hostname=$NAME/" > $CONF.new && mv $CONF.new $CONF
/sbin/zabbix-rebase-server