#!/bin/sh
# Script was taken from mysql323-server port, and modified
# to suit zabbix needs

[ -n "${PACKAGE_BUILDING}" ] && exit 0

PATH=/bin:/usr/sbin

USER=monitor
GROUP=${USER}

# change owner for installed empty directories
chown -R monitor:monitor /var/run/zabbix /var/log/zabbix
chown -R monitor:monitor /usr/local/etc/zabbix/{conf.d,bin}

# replace hostname in config file to FQDN
NAME=$(hostname -f)
HN_CONF=/usr/local/etc/zabbix/hostname.conf
PATH=/usr/bin:/usr/local/bin:/usr/local/sbin:$PATH

echo Hostname=$NAME > $HN_CONF
/usr/local/sbin/zabbix-rebase-server