#!/bin/sh
# PROVIDE: zabbix_agentd
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="zabbix_agentd"
rcvar=${name}_enable
load_rc_config $name
eval : \${${rcvar}='NO'}

command="/usr/local/sbin/${name}"
required_files="/usr/local/etc/zabbix/${name}.conf"
command_args="-c $required_files"

run_rc_command "$1"
